displayName=Camdozaal Vault Helper
author=JimothyPShrum
description=Finds optimal route for lockboxes in Camdozaal Vault
tags=camdozaal, vault, maze, solver, helper, lockbox
version=1.0
plugins=com.jimothypshrum.CamdozaalVaultHelperPlugin
build=standard
