package com.jimothypshrum;

import net.runelite.api.gameval.VarbitID;
import net.runelite.api.gameval.VarPlayerID;
import com.google.common.collect.ImmutableMap;

public class VarInfo
{
    static final ImmutableMap<Integer, String> VARBIT_IDS = new ImmutableMap.Builder<Integer, String>()
            .put(VarbitID.CAMDOZAAL_VAULT_BARRIER_A, "CAMDOZAAL_VAULT_BARRIER_A")
            .put(VarbitID.CAMDOZAAL_VAULT_BARRIER_B, "CAMDOZAAL_VAULT_BARRIER_B")
            .put(VarbitID.CAMDOZAAL_VAULT_BARRIER_C, "CAMDOZAAL_VAULT_BARRIER_C")
            .put(VarbitID.CAMDOZAAL_VAULT_BARRIER_D, "CAMDOZAAL_VAULT_BARRIER_D")
            .put(VarbitID.CAMDOZAAL_VAULT_BARRIER_E, "CAMDOZAAL_VAULT_BARRIER_E")
            .put(VarbitID.CAMDOZAAL_VAULT_BARRIER_F, "CAMDOZAAL_VAULT_BARRIER_F")
            .put(VarbitID.CAMDOZAAL_VAULT_BARRIER_G, "CAMDOZAAL_VAULT_BARRIER_G")
            .put(VarbitID.CAMDOZAAL_VAULT_CHEST_SMALL_1, "CAMDOZAAL_VAULT_CHEST_SMALL_1")
            .put(VarbitID.CAMDOZAAL_VAULT_CHEST_SMALL_2, "CAMDOZAAL_VAULT_CHEST_SMALL_2")
            .put(VarbitID.CAMDOZAAL_VAULT_CHEST_SMALL_3, "CAMDOZAAL_VAULT_CHEST_SMALL_3")
            .put(VarbitID.CAMDOZAAL_VAULT_CHEST_SMALL_4, "CAMDOZAAL_VAULT_CHEST_SMALL_4")
            .put(VarbitID.CAMDOZAAL_VAULT_CHEST_SMALL_5, "CAMDOZAAL_VAULT_CHEST_SMALL_5")
            .put(VarbitID.CAMDOZAAL_VAULT_CHEST_SMALL_6, "CAMDOZAAL_VAULT_CHEST_SMALL_6")
            .put(VarbitID.CAMDOZAAL_VAULT_CHEST_MEDIUM_1, "CAMDOZAAL_VAULT_CHEST_MEDIUM_1")
            .put(VarbitID.CAMDOZAAL_VAULT_CHEST_MEDIUM_2, "CAMDOZAAL_VAULT_CHEST_MEDIUM_2")
            .put(VarbitID.CAMDOZAAL_VAULT_CHEST_MEDIUM_3, "CAMDOZAAL_VAULT_CHEST_MEDIUM_3")
            .put(VarbitID.CAMDOZAAL_VAULT_CHEST_MEDIUM_4, "CAMDOZAAL_VAULT_CHEST_MEDIUM_4")
            .put(VarbitID.CAMDOZAAL_VAULT_CHEST_LARGE_1, "CAMDOZAAL_VAULT_CHEST_LARGE_1")
            .put(VarbitID.CAMDOZAAL_VAULT_CHEST_LARGE_2, "CAMDOZAAL_VAULT_CHEST_LARGE_2")
            .put(VarbitID.CAMDOZAAL_VAULT_CHEST_LARGE_3, "CAMDOZAAL_VAULT_CHEST_LARGE_3")
            .put(VarbitID.CAMDOZAAL_VAULT_CHESTS_MEDIUM, "CAMDOZAAL_VAULT_CHESTS_MEDIUM")
            .put(VarbitID.CAMDOZAAL_VAULT_WARNING, "CAMDOZAAL_VAULT_WARNING")
            .put(VarbitID.CAMDOZAAL_VAULT_TIME_REMAINING, "CAMDOZAAL_VAULT_TIME_REMAINING")
            .build();

    static final int VARPLAYER_ID = VarPlayerID.CAMDOZAAL_STORED_BARRONITE;

}
